import { useState } from 'react';
import { ocrDocument } from '../../services/api';
import { usePatientSession } from '../patient/state/PatientSessionContext';

export default function DocumentUpload(){
 const {documents,addDocument,removeDocument}=usePatientSession(); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 const process=async(file:File)=>{setBusy(true);setMessage(`Reading ${file.name}…`);try{const r=await ocrDocument(file);addDocument({id:crypto.randomUUID(),name:r.name,type:file.type||r.type,uploadedAt:r.processedAt,text:r.text,extractionStatus:r.extractionStatus==='extracted'?'extracted':'ocr',entities:r.entities,pages:r.pages,previewUrl:file.type.startsWith('image/')?URL.createObjectURL(file):undefined});setMessage(`${file.name} processed successfully.`);}catch(e){setMessage(e instanceof Error?e.message:'Could not process this document.');}finally{setBusy(false);}};
 const onFiles=(files:FileList|null)=>{if(!files?.length)return;const file=files[0];if(file.size>8*1024*1024){setMessage('Please choose a file smaller than 8 MB.');return;}void process(file);};
 return <section className="rounded-2xl border border-clinic-100 bg-white p-6 shadow-sm">
  <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-display text-xl font-semibold text-ink">Previous medical records</h2><p className="mt-1 text-sm text-muted">Upload a prescription, lab report or discharge summary. Images and PDFs are processed by the OCR service.</p></div><button onClick={()=>addDocument({id:crypto.randomUUID(),name:'Demo_Lab_Report.txt',type:'text/plain',uploadedAt:new Date().toISOString(),text:'Date: 14 Aug 2026\nHemoglobin: 10.2 g/dL\nGlucose: 156 mg/dL\nMedication: Metformin 500 mg\nHistory: Diabetes',extractionStatus:'extracted',entities:[{type:'Investigation',value:'Hemoglobin: 10.2 g/dL',confidence:'high',sourceText:'Hemoglobin: 10.2 g/dL',page:1},{type:'Investigation',value:'Glucose: 156 mg/dL',confidence:'high',sourceText:'Glucose: 156 mg/dL',page:1},{type:'Medication',value:'Metformin',confidence:'high',sourceText:'Medication: Metformin 500 mg',page:1},{type:'Diagnosis/History',value:'Diabetes',confidence:'medium',sourceText:'History: Diabetes',page:1}],pages:[{page:1,text:'Date: 14 Aug 2026\nHemoglobin: 10.2 g/dL\nGlucose: 156 mg/dL\nMedication: Metformin 500 mg\nHistory: Diabetes',confidence:'high'}]})} className="rounded-full border border-clinic-200 px-4 py-2 text-sm font-medium text-clinic-700">Add demo report</button></div>
  <label className="mt-5 block cursor-pointer rounded-xl border-2 border-dashed border-clinic-200 p-8 text-center hover:bg-clinic-50"><span className="font-medium text-clinic-700">Choose image, PDF or text document</span><span className="mt-1 block text-sm text-muted">Maximum 8 MB</span><input className="sr-only" type="file" accept=".pdf,.txt,.csv,.md,image/*" onChange={e=>onFiles(e.target.files)}/></label>
  {busy&&<p className="mt-3 text-sm text-muted">{message}</p>}{!busy&&message&&<p className="mt-3 text-sm text-clinic-700">{message}</p>}
  <div className="mt-5 space-y-4">{documents.map(doc=><DocumentCard key={doc.id} doc={doc} onRemove={()=>removeDocument(doc.id)}/>)}</div>
 </section>
}
function DocumentCard({doc,onRemove}:{doc:any;onRemove:()=>void}){const [show,setShow]=useState(false);const [selected,setSelected]=useState<any|null>(null);const sourceText=selected?.sourceText||'';const source=doc.text||'';let preview=source;if(sourceText){const idx=source.toLowerCase().indexOf(sourceText.toLowerCase());if(idx>=0)preview=<><span>{source.slice(0,idx)}</span><mark className="rounded bg-yellow-200 px-1 text-ink">{source.slice(idx,idx+sourceText.length)}</mark><span>{source.slice(idx+sourceText.length)}</span></>;}return <article className="rounded-xl border border-clinic-100 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-medium text-ink">{doc.name}</p><p className="text-xs text-muted">📄 Scanned report → OCR → structured data · {doc.extractionStatus === 'ocr' ? 'OCR processed' : doc.extractionStatus==='extracted' ? 'Text extracted' : 'Preview only'} · {new Date(doc.uploadedAt).toLocaleString()}</p></div><button onClick={onRemove} className="text-sm text-flag-700">Remove</button></div>
 {doc.entities.length>0&&<div className="mt-3 flex flex-wrap gap-2">{doc.entities.map((e:any,i:number)=><button type="button" onClick={()=>setSelected(e)} key={i} className={`rounded-full px-3 py-1 text-xs ${e.confidence==='high'?'bg-clinic-50 text-clinic-800':'bg-amber-50 text-amber-800'}`}>{e.type}: {e.value}</button>)}</div>}
 <button onClick={()=>setShow(!show)} className="mt-4 text-sm font-medium text-clinic-700">{show?'Hide evidence':'View extracted evidence'}</button>
 {show&&<div className="mt-3 space-y-3"><div className="max-h-44 overflow-auto rounded-lg bg-canvas p-3 text-xs text-muted whitespace-pre-wrap">{preview||'No text extracted.'}</div>{selected&&<p className="text-xs text-muted">Selected evidence: {selected.type} · confidence {selected.confidence}{selected.page?` · page ${selected.page}`:''}</p>}<div className="grid gap-3 sm:grid-cols-2">{doc.entities.map((e:any,i:number)=><button type="button" onClick={()=>setSelected(e)} key={i} className="rounded-lg border border-clinic-50 p-3 text-left hover:bg-clinic-50"><p className="text-sm font-medium text-ink">{e.value}</p><p className="text-xs text-muted">Source: {e.sourceText} · {e.confidence}{e.page?` · page ${e.page}`:''}</p></button>)}</div></div>}
 </article>}
